# Generated by Django 5.2.6 on 2025-09-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
