# Generated by Django 5.2.6 on 2025-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_blog_comment_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='uploads/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
