# Generated by Django 5.2.6 on 2025-09-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='webapp.reply'),
        ),
    ]
